apiVersion: v1
kind: Pod
metadata:
  name: employee-database
  labels:
    name: employee-database
    app:  emp-service-app
spec:
  containers:
  - name: mongo
    image: mongo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017