apiVersion: v1
kind: Service
metadata:
  name: emp-db
  labels:
    name: emp-db-service
    app: emp-service-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: employee-database
    app: emp-service-app
