apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    name: emp-service
    app:  emp-service-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    name: emp-service-pod
    app:  emp-service-app
      