apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-cliam
  labels:
    app: mongo
spec:
  resources:
    requests:
      storage: 250Mi
  storageClassName: manual
  accessModes:
    - "ReadWriteMany"
